# default parameters
seed = 10
name = 'albert_large_domain_classification_ft_multiwoz'
retain_ckp = true
# [PARAMSGRID]
# MODEL_-attn_mode=[
# ]
[EXPERIMENT]
accelerator = 'gpu'
batch_size = 32
epochs = 3
save_path = 'results/experiments/ft/'
optimizer = 'adamw'
optimizer_params = {}
lrscheduler = 'constantwarmup'
lrscheduler_params={}
lr = 0.00005
warmup = 0.1
# steps = 3000
stop_strategy = 'epoch_stop'
stop_patience = 10
monitor = 'val_loss'
mode = 'min'
temperature = 20
str_name = 'dc_multiwoz_no_adjust_labels'

[TEACHERS]
teacher_list = ['t1']
t1 = {type='ALBERT',name='albert-large-v1',head={type='dc',nclasses=8},freeze=false}

[DATA]
names = ['MultiWozDCIDSFPOSDataset']
num_workers = 4
max_seq_len = 512







